name: medicaments_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.3
  date_time_picker: ^2.1.0
  badges: ^2.0.1
  flutter_bloc: ^7.3.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^9.1.2
  rxdart: ^0.27.2
  flutter_native_timezone: ^2.0.0
  uuid: ^3.0.5
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  bloc_test: ^8.5.0
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2

flutter_icons:
  image_path: assets/images/medication.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  generate: true
